### ISSUE TITLE
Create manifest file for assets

### ISSUE THREAD

**Issue by estahn** [vanetix/grunt-asset-revisions#1]
We currently use sprockets but want to migrate to Grunt. Sprockets generates a manifest file (manifest.yml) which contains the mapping between regular files and their revisions, e.g.

``` yml

---
modernizr.js: modernizr-675401327c4abfdfea3b2bd1473e11c1.js
foundation/jquery.autocomplete.js: foundation/jquery.autocomplete-115d164f0dced38ffca59a7807dbafd6.js
...
app.js: app-9b08c2d875eb42c140cd5e9c0e6f1ac3.js
app.css: app-ff1d2f8fc1e22b59342316d9cac2bf6b.css
```

Something similar in whatever format would be great.
